// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlD56flqtD2_L-PjDMjeGikJLi1xiD-l0',
    appId: '1:1479652704:web:855fc93f179a1e9eb31a05',
    messagingSenderId: '1479652704',
    projectId: 'appwrite-messaging-70c26',
    authDomain: 'appwrite-messaging-70c26.firebaseapp.com',
    storageBucket: 'appwrite-messaging-70c26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUF8BenWRR0WqqYd3Aq9AG0odfQdlfbYE',
    appId: '1:1479652704:android:8420ebf932216b63b31a05',
    messagingSenderId: '1479652704',
    projectId: 'appwrite-messaging-70c26',
    storageBucket: 'appwrite-messaging-70c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtn-a25aBFCZjbAOfSXDNmz8PWvD6W8A',
    appId: '1:1479652704:ios:d49c34cc08ee9259b31a05',
    messagingSenderId: '1479652704',
    projectId: 'appwrite-messaging-70c26',
    storageBucket: 'appwrite-messaging-70c26.firebasestorage.app',
    iosBundleId: 'com.example.messengerClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtn-a25aBFCZjbAOfSXDNmz8PWvD6W8A',
    appId: '1:1479652704:ios:d49c34cc08ee9259b31a05',
    messagingSenderId: '1479652704',
    projectId: 'appwrite-messaging-70c26',
    storageBucket: 'appwrite-messaging-70c26.firebasestorage.app',
    iosBundleId: 'com.example.messengerClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlD56flqtD2_L-PjDMjeGikJLi1xiD-l0',
    appId: '1:1479652704:web:a3022759eac8571eb31a05',
    messagingSenderId: '1479652704',
    projectId: 'appwrite-messaging-70c26',
    authDomain: 'appwrite-messaging-70c26.firebaseapp.com',
    storageBucket: 'appwrite-messaging-70c26.firebasestorage.app',
  );
}
